### ISSUE TITLE
Auftrag vom 10.03.16

### ISSUE THREAD

**Issue by Kornek** [htl-leonding/2016_3chif_carduino#2]
An: Schicker, Mair, Mistlberger 
Aufgabe:    JavaFX
Views für Modi implementiren:  
*Serial - via Kabel zu "Debuggen" 
*Client - zum steuern
*mit Startbildschirm
für jeden Punkt jeweils eine View
Termin:  bis zur nächsten Vorstellung, etwas vorweisen können!

**Comment by Kornek** [comment]
GELESEN

**Comment by htl-leonding** [comment]
Da bin ich ja gespannt, welche Arbeitsergebnisse Ihr vorweisen könnt
